---
version: 2
jobs:
  BASE: &base # Only used to centralized some common configs
    docker:
      - image: node:latest
    working_directory: ~/cli
  CI: &test
    <<: *base
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build plugin
          command: npm run prepack
      - run:
          name: Testing
          command: npm run test
      - persist_to_workspace:
          root: ~/cli
          paths:
            - lib
  cache:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules

  bumpprerelease:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - attach_workspace:
          at: ~/cli
      - run:
          name: Bump Preminor
          command: npm run bumpprerelease

  publish:
    <<: *base
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - attach_workspace:
          at: ~/cli
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  'New Code Checks':
    jobs:
      - CI:
          filters:
            branches:
              ignore:
                - main
                - develop
      - cache:
          requires:
            - CI

          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/
  'Develop Checks':
    jobs:
      - CI:
          filters:
            branches:
              only: develop
      - bumpprerelease:
          requires:
            - CI
      - cache:
          requires:
            - CI

  'Main Checks':
    jobs:
      - CI:
          filters:
            branches:
              only: main
      # - Version:
      #     requires:
      #       - CI
      - cache:
          requires:
            - CI
  'Publish':
    jobs:
      - CI:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          requires:
            - CI
      - cache:
          requires:
            - CI
