---
version: 2.1
orbs:
  gh: circleci/github-cli@2.1.1

jobs:
  installdeps:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules

  CI: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Build plugin
          command: npm run build
      - run:
          name: Testing
          command: npm run test
      - persist_to_workspace:
          root: ~/cli
          paths:
            - lib

  bumpprerelease:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - attach_workspace:
          at: ~/cli
      - run:
          name: Set Git Creds
          command: git config user.email "gael.motte@gmail.com" && git config user.name "Gael Motte"
      - add_ssh_keys:
          fingerprints:
            - 'c3:9a:d1:80:21:fb:38:02:1c:65:77:03:51:c2:0e:37'
      - run:
          name: Bump Preminor
          command: npm run bumpprerelease

  bumpversion:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - gh/setup
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - attach_workspace:
          at: ~/cli
      - run:
          name: Set Git Creds
          command: git config user.email "gael.motte@gmail.com" && git config user.name "Gael Motte"
      - add_ssh_keys:
          fingerprints:
            - 'c3:9a:d1:80:21:fb:38:02:1c:65:77:03:51:c2:0e:37'
      - run:
          name: Bump Minor or Patch
          command: npm run bumpversion
      - run:
          command: |
            D=$(date +'%Y-%m-%d-%H-%M'); 
            B="merge-back-$D";  
            git checkout -b $B && git push --set-upstream origin $B \\
            &&  git checkout gh pr create --title "Merge back $D" -B develop -H main -b "Make sure to keep the most advanced version number when handling the merge over the various conflicted files, if any"
          name: Create Pull Request for merge back

  publishtonpm:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - attach_workspace:
          at: ~/cli
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  'New Code Checks':
    jobs:
      - installdeps:
          filters:
            branches:
              ignore:
                - main
                - develop
      - CI:
          requires:
            - installdeps
  'Develop Checks':
    jobs:
      - installdeps:
          filters:
            branches:
              only: develop
      - CI:
          requires:
            - installdeps
      - bumpprerelease:
          requires:
            - CI

  'Main Checks':
    jobs:
      - installdeps:
          filters:
            branches:
              only: main
      - CI:
          requires:
            - installdeps
      - bumpversion:
          requires:
            - CI

  'Publish':
    jobs:
      - installdeps:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publishtonpm:
          requires:
            - installdeps
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
